#!/usr/bin/env bash
set -euo pipefail

set -euo pipefail

function perf_profile {
  local name="$1"
  echo ">>> PERF + KCachegrind for ${name}..."
  perf record -F 99 -g -- ./lgp
  perf stat -d -- ./lgp || true
  perf script -s perf2calltree.py > report-perf-${name}.calltree
}

function gprof_profile {
  local name="$1"
  echo ">>> GPROF for ${name}..."
  ./lgp
  gprof ./lgp gmon.out > report-gprof-${name}.txt
  rm -f gmon.out
}

function callgrind_profile {
  local name="$1"
  valgrind --tool=callgrind --dump-instr=yes --simulate-cache=yes ./lgp
  callgrind_annotate --auto=yes callgrind.out.* > report-callgrind-${name}.txt
  rm callgrind.out.*
}

function causal_profile {
  local name="$1"
  echo ">>> Coz Causal Profiler for ${name}"
  coz record -o coz-${name}.coz -- ./lgp
  coz report --html report-coz-${name}.html
}

function evaluate {
  local name="$1"
  make clean
  make "$name"
  perf_profile "$name"
  gprof_profile "$name"
  callgrind_profile "$name"
  causal_profile "$name" || echo "Coz non installato"
}

evaluate avx512
evaluate avx2
evaluate sse2
evaluate single
